hydra:
  job:
    chdir: True

model_type: "hrnet"

# Model-specific settings
model:

  # ResUNet specific parameters
  resunet:
    layers: 4                  # Number of layers in the network (only used if no backbone)
    filters: 24                # Number of starting filters (only used if no backbone)
    backbone: resnet34             # Options: null, resnet18, resnet34, resnet50, resnet101, resnet152
    dilated: true             # Whether to use dilated convolutions
    pretrained: true           # Whether to use pretrained backbone weights
  
  # PSPNet specific parameters
  pspnet:
    backbone: "resnet34"
    dilated: True
      
  # HRNetV2+OCR specific parameters
  hrnet:
    backbone: "hrnetv2_w18"    # Options: hrnetv2_w18, hrnetv2_w32, hrnetv2_w48
    pretrained: True           # Whether to use pretrained backbone weights
    ocr_mid_channels: 512      # Number of channels in OCR module
    dropout: 0.1               # Dropout rate for the model
    use_aux_head: True         # Whether to use auxiliary segmentation head during training

# Training settings
train:
  epochs: 80
  patch_size: 384
  batch_size: 64
  LR: 0.001
  scheduler_patience: 4
  val_steps: 30
  test_every: 1
  amp: False
  gradient_clipping: 1.0

  # Loss configuration
  loss:
    type: "combined"  # Options: crossentropy, focal, dice, combined
    
    # CrossEntropy loss parameters
    crossentropy:
      reduction: "mean"
      label_smoothing: 0.0
      # weight: null  # Optional class weights tensor
    
    # Focal loss parameters
    focal:
      alpha: null  # Can be float, list of floats, or null for no weighting
      gamma: 2.0
      reduction: "mean"
    
    # Dice loss parameters
    dice:
      smooth: 1.0
      reduction: "mean"
      include_background: true
    
    # Combined loss configuration
    combined:
      losses:
        dice:
          type: "dice"
          smooth: 1.0
          reduction: "mean"
          include_background: true
        focal:
          type: "focal"
          alpha: null
          gamma: 2.0
          reduction: "mean"
      weights:
        dice: 0.6
        focal: 0.4

  augm:
    rotation: 20
    scale: 0.1
    brightness: 0.01
    color: 0.02
    factor: 10

  balancer:
    enabled: false
    class_area_consideration: 1.5
    patch_positioning_accuracy: 0.8
    balancing_strength: 0.75
    void_border_width: 4
    acceleration: 8
  
  data_loader:
    num_workers: 4
    prefetch_factor: 8
    pin_memory: true

# Data settings
data:
  classes: "S1_S2"
  cache_path: "${oc.env:HOME}/.cache/petroscope-data"
  dataset_path: "${oc.env:HOME}/dev/LumenStone/S1v2_S2v2_x05/"

# Test settings
test:
  void_pad: 4
  void_border_width: 2
  vis_segmentation: true
  max_epoch_visualizations: 15  # Keep visualizations for only the last N epochs

# Hardware settings
hardware:
  device: "cuda:2"
  seed: 42
